# Generated by Django 5.0.2 on 2024-03-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_upload_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
