# Generated by Django 5.0.2 on 2024-03-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
    ]
